// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chpypuevfoddszfosols.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNocHlwdWV2Zm9kZHN6Zm9zb2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjk2NzQsImV4cCI6MjA2NDk0NTY3NH0.gTlRTHmNTPffi2WX5lMzFtURkfdKAQBdG3UJDXP9pYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);